// Package rules provides the AML rule DSL layer and the starter rule library.
package rules

import "github.com/luxfi/aml/pkg/types"

// StarterRules returns the 20 default AML rules covering standard typologies.
// These are seeded on first run for every org. Admins can disable or modify.
func StarterRules(orgID string) []types.Rule {
	return []types.Rule{
		{
			ID:          "rule-ctr-threshold",
			OrgID:       orgID,
			Name:        "CTR Threshold",
			Description: "Currency Transaction Report: transactions over $10,000 USD equivalent",
			DSL:         `notional_usd(tx) > 10000`,
			Severity:    types.SeverityHigh,
			Weight:      0.3,
			Action:      types.ActionReport,
			Enabled:     true,
			Priority:    1,
		},
		{
			ID:          "rule-structuring",
			OrgID:       orgID,
			Name:        "Structuring",
			Description: "Transactions just below CTR threshold — possible structuring",
			DSL:         `tx.Notional >= 9000 && tx.Notional < 10000`,
			Severity:    types.SeverityMedium,
			Weight:      0.25,
			Action:      types.ActionFlag,
			Enabled:     true,
			Priority:    2,
		},
		{
			ID:          "rule-velocity-daily",
			OrgID:       orgID,
			Name:        "Velocity Daily",
			Description: "Daily transaction volume exceeds $50,000",
			DSL:         `sum_last_24h(tx.UserID) > 50000`,
			Severity:    types.SeverityMedium,
			Weight:      0.2,
			Action:      types.ActionReview,
			Enabled:     true,
			Priority:    3,
		},
		{
			ID:          "rule-velocity-monthly",
			OrgID:       orgID,
			Name:        "Velocity Monthly",
			Description: "Monthly transaction volume exceeds $500,000",
			DSL:         `sum_last_30d(tx.UserID) > 500000`,
			Severity:    types.SeverityHigh,
			Weight:      0.25,
			Action:      types.ActionReview,
			Enabled:     true,
			Priority:    4,
		},
		{
			ID:          "rule-first-time-large",
			OrgID:       orgID,
			Name:        "First-Time Large",
			Description: "First transaction from user exceeds $25,000",
			DSL:         `first_tx(tx.UserID) && tx.Notional > 25000`,
			Severity:    types.SeverityMedium,
			Weight:      0.2,
			Action:      types.ActionReview,
			Enabled:     true,
			Priority:    5,
		},
		{
			ID:          "rule-round-trip",
			OrgID:       orgID,
			Name:        "Round-Trip",
			Description: "Funds sent and received within 24h — layering indicator",
			DSL:         `is_round_trip(tx.UserID, "24h")`,
			Severity:    types.SeverityMedium,
			Weight:      0.2,
			Action:      types.ActionFlag,
			Enabled:     true,
			Priority:    6,
		},
		{
			ID:          "rule-sanctioned-jurisdiction",
			OrgID:       orgID,
			Name:        "Sanctioned Jurisdiction",
			Description: "Entity located in a sanctioned jurisdiction",
			DSL:         `entity.Jurisdiction in sanctioned_jurisdictions()`,
			Severity:    types.SeverityCritical,
			Weight:      0.5,
			Action:      types.ActionBlock,
			Enabled:     true,
			Priority:    7,
		},
		{
			ID:          "rule-pep-large",
			OrgID:       orgID,
			Name:        "PEP Large Transaction",
			Description: "Politically exposed person transacting over $10,000",
			DSL:         `entity.PEP == true && tx.Notional > 10000`,
			Severity:    types.SeverityHigh,
			Weight:      0.3,
			Action:      types.ActionReview,
			Enabled:     true,
			Priority:    8,
		},
		{
			ID:          "rule-unusual-hour",
			OrgID:       orgID,
			Name:        "Unusual Hour",
			Description: "Transaction during unusual hours (2-4 AM local time)",
			DSL:         `hour(tx.Timestamp, entity.Jurisdiction) in [2, 3, 4]`,
			Severity:    types.SeverityLow,
			Weight:      0.1,
			Action:      types.ActionFlag,
			Enabled:     true,
			Priority:    9,
		},
		{
			ID:          "rule-new-counterparty-large",
			OrgID:       orgID,
			Name:        "New Counterparty Large",
			Description: "First transaction with counterparty exceeds $5,000",
			DSL:         `first_counterparty(tx.UserID, tx.Counterparty) && tx.Notional > 5000`,
			Severity:    types.SeverityMedium,
			Weight:      0.15,
			Action:      types.ActionReview,
			Enabled:     true,
			Priority:    10,
		},
		{
			ID:          "rule-dormant-reactivation",
			OrgID:       orgID,
			Name:        "Dormant Reactivation",
			Description: "Account dormant >180 days reactivated with large transaction",
			DSL:         `last_tx_age(tx.UserID) > 180 && tx.Notional > 10000`,
			Severity:    types.SeverityMedium,
			Weight:      0.2,
			Action:      types.ActionReview,
			Enabled:     true,
			Priority:    11,
		},
		{
			ID:               "rule-crypto-mixer",
			OrgID:            orgID,
			Name:             "Crypto Mixer Address",
			Description:      "Counterparty is a known mixer address",
			DSL:              `is_mixer_address(tx.Counterparty)`,
			Severity:         types.SeverityCritical,
			Weight:           0.5,
			Action:           types.ActionBlock,
			Enabled:          true,
			Priority:         12,
			AssetClassFilter: []string{"us_crypto", "crypto"},
		},
		{
			ID:               "rule-darknet-market",
			OrgID:            orgID,
			Name:             "Darknet Market",
			Description:      "Counterparty is a known darknet marketplace",
			DSL:              `is_darknet_market(tx.Counterparty)`,
			Severity:         types.SeverityCritical,
			Weight:           0.5,
			Action:           types.ActionBlock,
			Enabled:          true,
			Priority:         13,
			AssetClassFilter: []string{"us_crypto", "crypto"},
		},
		{
			ID:          "rule-ip-geo-mismatch",
			OrgID:       orgID,
			Name:        "IP/Geo Mismatch",
			Description: "Transaction IP does not match entity jurisdiction",
			DSL:         `!geo_match(tx.IPAddress, entity.Jurisdiction)`,
			Severity:    types.SeverityLow,
			Weight:      0.1,
			Action:      types.ActionFlag,
			Enabled:     true,
			Priority:    14,
		},
		{
			ID:          "rule-layering",
			OrgID:       orgID,
			Name:        "Layering Pattern",
			Description: "Layering score exceeds 0.8 — complex transaction chains",
			DSL:         `layering_score(tx.UserID) > 0.8`,
			Severity:    types.SeverityHigh,
			Weight:      0.3,
			Action:      types.ActionReview,
			Enabled:     true,
			Priority:    15,
		},
		{
			ID:          "rule-smurfing",
			OrgID:       orgID,
			Name:        "Smurfing",
			Description: "Multiple small deposits across accounts — smurfing pattern",
			DSL:         `smurfing_detected(tx.UserID, "7d")`,
			Severity:    types.SeverityHigh,
			Weight:      0.3,
			Action:      types.ActionReview,
			Enabled:     true,
			Priority:    16,
		},
		{
			ID:          "rule-wash-trading",
			OrgID:       orgID,
			Name:        "Wash Trading",
			Description: "Self-trading detected within 1h window",
			DSL:         `wash_trade_detected(tx.Symbol, "1h")`,
			Severity:    types.SeverityMedium,
			Weight:      0.2,
			Action:      types.ActionFlag,
			Enabled:     true,
			Priority:    17,
		},
		{
			ID:          "rule-sanctions-direct",
			OrgID:       orgID,
			Name:        "Sanctions Direct",
			Description: "Entity name matches sanctions list",
			DSL:         `sanctions_hit(entity.Name, entity.Jurisdiction)`,
			Severity:    types.SeverityCritical,
			Weight:      0.5,
			Action:      types.ActionBlock,
			Enabled:     true,
			Priority:    18,
		},
		{
			ID:          "rule-sanctions-counterparty",
			OrgID:       orgID,
			Name:        "Sanctions Counterparty",
			Description: "Counterparty name matches sanctions list",
			DSL:         `sanctions_hit(tx.Counterparty, "")`,
			Severity:    types.SeverityCritical,
			Weight:      0.5,
			Action:      types.ActionBlock,
			Enabled:     true,
			Priority:    19,
		},
		{
			ID:          "rule-travel-rule",
			OrgID:       orgID,
			Name:        "Travel Rule",
			Description: "Transaction exceeds FATF Travel Rule threshold ($3,000 USD equivalent)",
			DSL:         `notional_usd(tx) > 3000`,
			Severity:    types.SeverityMedium,
			Weight:      0.15,
			Action:      types.ActionReport,
			Enabled:     true,
			Priority:    20,
		},
		{
			ID:          "rule-travel-rule-incomplete",
			OrgID:       orgID,
			Name:        "Travel Rule Incomplete",
			Description: "Travel rule triggered but originator/beneficiary info missing",
			DSL:         `tx.Notional > travel_rule_threshold(tx.Currency) && !travel_rule_complete(tx.ID)`,
			Severity:    types.SeverityHigh,
			Weight:      0.25,
			Action:      types.ActionReview,
			Enabled:     true,
			Priority:    21,
		},
		{
			ID:               "rule-chain-risk",
			OrgID:            orgID,
			Name:             "Chain Risk Check",
			Description:      "Counterparty address flagged by blockchain analytics",
			DSL:              `chain_risk_score(tx.Counterparty) > 0.7`,
			Severity:         types.SeverityHigh,
			Weight:           0.35,
			Action:           types.ActionBlock,
			Enabled:          true,
			Priority:         22,
			AssetClassFilter: []string{"us_crypto", "crypto"},
		},
		{
			ID:               "rule-chain-sanctions",
			OrgID:            orgID,
			Name:             "Chain Sanctions",
			Description:      "Counterparty address is sanctions-listed on-chain",
			DSL:              `chain_is_sanctioned(tx.Counterparty)`,
			Severity:         types.SeverityCritical,
			Weight:           0.5,
			Action:           types.ActionBlock,
			Enabled:          true,
			Priority:         23,
			AssetClassFilter: []string{"us_crypto", "crypto"},
		},
	}
}
